import { Order } from "./types";

const NOW = Date.now();

export const ORDERS_SEED: Order[] = [
  {
    _id: "66c1e001ab000001",
    orderType: "TABLE",
    orderStatus: "PROGRESS",
    paymentStatus: "UNPAID",
    paymentMethod: "CARD",
    orderTotal: 32000,
    deliveryFee: 0,
    tableId: "12",
    memberId: null,
    orderNote: "No onions",
    createdAt: new Date(NOW - 30 * 60 * 1000).toISOString(),
    updatedAt: new Date(NOW - 20 * 60 * 1000).toISOString(),
  },
  {
    _id: "66c1e001ab000002",
    orderType: "DELIVERY",
    orderStatus: "PENDING",
    paymentStatus: "UNPAID",
    paymentMethod: "TRANSFER",
    orderTotal: 22000,
    deliveryFee: 3000,
    tableId: null,
    memberId: "M-4821",
    orderNote: "Leave at door",
    createdAt: new Date(NOW - 90 * 60 * 1000).toISOString(),
    updatedAt: new Date(NOW - 88 * 60 * 1000).toISOString(),
  },
  {
    _id: "66c1e001ab000003",
    orderType: "TABLE",
    orderStatus: "COMPLETED",
    paymentStatus: "PAID",
    paymentMethod: "CASH",
    orderTotal: 15000,
    deliveryFee: 0,
    tableId: "4",
    memberId: null,
    orderNote: "",
    createdAt: new Date(NOW - 200 * 60 * 1000).toISOString(),
    updatedAt: new Date(NOW - 180 * 60 * 1000).toISOString(),
  },
  {
    _id: "66c1e001ab000004",
    orderType: "TAKEOUT",
    orderStatus: "CANCELLED",
    paymentStatus: "REFUNDED",
    paymentMethod: "CARD",
    orderTotal: 12000,
    deliveryFee: 0,
    tableId: null,
    memberId: "M-7330",
    orderNote: "Allergic to peanuts",
    createdAt: new Date(NOW - 300 * 60 * 1000).toISOString(),
    updatedAt: new Date(NOW - 290 * 60 * 1000).toISOString(),
  },
  {
    _id: "66c1e001ab000005",
    orderType: "DELIVERY",
    orderStatus: "PROGRESS",
    paymentStatus: "PAID",
    paymentMethod: "TRANSFER",
    orderTotal: 28000,
    deliveryFee: 3000,
    tableId: null,
    memberId: "M-9910",
    orderNote: "",
    createdAt: new Date(NOW - 400 * 60 * 1000).toISOString(),
    updatedAt: new Date(NOW - 380 * 60 * 1000).toISOString(),
  },
];
